"""Initial schema

Revision ID: 5fa4b01cf373
Revises: 
Create Date: 2026-04-27 13:40:32.801797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa4b01cf373'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contratistas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_contratistas_id'), 'contratistas', ['id'], unique=False)
    op.create_table('usuarios_app',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_app_email'), 'usuarios_app', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_app_id'), 'usuarios_app', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_app_username'), 'usuarios_app', ['username'], unique=True)
    op.create_table('lotes_archivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('hash_archivo', sa.String(length=64), nullable=False),
    sa.Column('contratista_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('subido_por', sa.Integer(), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('detalle_error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contratista_id'], ['contratistas.id'], ),
    sa.ForeignKeyConstraint(['subido_por'], ['usuarios_app.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lotes_archivos_hash_archivo'), 'lotes_archivos', ['hash_archivo'], unique=False)
    op.create_index(op.f('ix_lotes_archivos_id'), 'lotes_archivos', ['id'], unique=False)
    op.create_table('partes_diarios_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('fila_excel', sa.Integer(), nullable=False),
    sa.Column('id_externo', sa.String(length=100), nullable=True),
    sa.Column('id_parte_hash', sa.String(length=64), nullable=False),
    sa.Column('datos_crudos', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes_archivos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partes_diarios_raw_id'), 'partes_diarios_raw', ['id'], unique=False)
    op.create_index(op.f('ix_partes_diarios_raw_id_externo'), 'partes_diarios_raw', ['id_externo'], unique=False)
    op.create_index(op.f('ix_partes_diarios_raw_id_parte_hash'), 'partes_diarios_raw', ['id_parte_hash'], unique=False)
    op.create_table('partes_diarios_procesados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_id', sa.Integer(), nullable=False),
    sa.Column('id_parte_hash', sa.String(length=64), nullable=False),
    sa.Column('suministro', sa.String(length=50), nullable=True),
    sa.Column('fecha_ejecucion', sa.DateTime(), nullable=True),
    sa.Column('nro_medidor_retirado', sa.String(length=50), nullable=True),
    sa.Column('nro_medidor_colocado', sa.String(length=50), nullable=True),
    sa.Column('ord_nro', sa.Integer(), nullable=True),
    sa.Column('cod_epec', sa.Integer(), nullable=True),
    sa.Column('id_estado', sa.Integer(), nullable=False),
    sa.Column('traza_calidad', sa.String(length=100), nullable=False),
    sa.Column('cod_epec_sugerido', sa.Integer(), nullable=True),
    sa.Column('diferencia_uses', sa.Float(), nullable=True),
    sa.Column('tipo_discrepancia', sa.String(length=50), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('fue_corregido', sa.Boolean(), nullable=False),
    sa.Column('anulado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['raw_id'], ['partes_diarios_raw.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_id')
    )
    op.create_index(op.f('ix_partes_diarios_procesados_id'), 'partes_diarios_procesados', ['id'], unique=False)
    op.create_index(op.f('ix_partes_diarios_procesados_id_parte_hash'), 'partes_diarios_procesados', ['id_parte_hash'], unique=True)
    op.create_index(op.f('ix_partes_diarios_procesados_ord_nro'), 'partes_diarios_procesados', ['ord_nro'], unique=False)
    op.create_index(op.f('ix_partes_diarios_procesados_suministro'), 'partes_diarios_procesados', ['suministro'], unique=False)
    op.create_table('auditoria_cambios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parte_procesado_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('campo_modificado', sa.String(length=50), nullable=False),
    sa.Column('valor_anterior', sa.String(), nullable=True),
    sa.Column('valor_nuevo', sa.String(), nullable=True),
    sa.Column('motivo', sa.String(), nullable=False),
    sa.Column('fecha_cambio', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('version_resultante', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parte_procesado_id'], ['partes_diarios_procesados.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios_app.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_cambios_id'), 'auditoria_cambios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auditoria_cambios_id'), table_name='auditoria_cambios')
    op.drop_table('auditoria_cambios')
    op.drop_index(op.f('ix_partes_diarios_procesados_suministro'), table_name='partes_diarios_procesados')
    op.drop_index(op.f('ix_partes_diarios_procesados_ord_nro'), table_name='partes_diarios_procesados')
    op.drop_index(op.f('ix_partes_diarios_procesados_id_parte_hash'), table_name='partes_diarios_procesados')
    op.drop_index(op.f('ix_partes_diarios_procesados_id'), table_name='partes_diarios_procesados')
    op.drop_table('partes_diarios_procesados')
    op.drop_index(op.f('ix_partes_diarios_raw_id_parte_hash'), table_name='partes_diarios_raw')
    op.drop_index(op.f('ix_partes_diarios_raw_id_externo'), table_name='partes_diarios_raw')
    op.drop_index(op.f('ix_partes_diarios_raw_id'), table_name='partes_diarios_raw')
    op.drop_table('partes_diarios_raw')
    op.drop_index(op.f('ix_lotes_archivos_id'), table_name='lotes_archivos')
    op.drop_index(op.f('ix_lotes_archivos_hash_archivo'), table_name='lotes_archivos')
    op.drop_table('lotes_archivos')
    op.drop_index(op.f('ix_usuarios_app_username'), table_name='usuarios_app')
    op.drop_index(op.f('ix_usuarios_app_id'), table_name='usuarios_app')
    op.drop_index(op.f('ix_usuarios_app_email'), table_name='usuarios_app')
    op.drop_table('usuarios_app')
    op.drop_index(op.f('ix_contratistas_id'), table_name='contratistas')
    op.drop_table('contratistas')
    # ### end Alembic commands ###
